### ISSUE TITLE
maap

### ISSUE THREAD

**Issue by kuprusi** [Silverzonegames/Steampunk#2]
kun avaa mapin painamalla M näytölle tulee valkoinen neliö joka ei lähde pois mistään napista

**Comment by luukasp** [comment]
Hi, could you tell us what version are you using? Thanks

**Comment by luukasp** [comment]
Yeah, we are going to address that issue along with a bunch of other issues next update.

**Comment by slimerplanet** [comment]
The issue has been fixed
