### ISSUE TITLE
Item disappear and weird world

### ISSUE THREAD

**Issue by Mokky0** [Silverzonegames/Steampunk#3]
Some Items that I tried to pick up just disappeared to nowhere.
Also, the world (ground) has these weird cube-shaped objects that are grey.

-Mokky

**Comment by luukasp** [comment]
The items have probably went to the Player inventory, which is currently in development. I believe the cube shaped objects are used as pathfinding tests/scale reference or object placeholders. I will look into this though, if something's wrong, we'll fix it for the next release.

~Lucas (Neko/Da~ling)

**Comment by luukasp** [comment]
The issue at hand has been addressed in a development build, and the fix will be rolled out in the next preview beta.

~Lucas (Neko/Da~ling)
