### ISSUE TITLE
Flashlight points right

### ISSUE THREAD

**Issue by luukasp** [Silverzonegames/Steampunk#5]
The flashlight item points always to the right, regardless of the cursor's relative location to the player.
Here are screenshots of the bug occurring.
The bug occurs on v0.7
![Screenshot_20230103_065725](https://user-images.githubusercontent.com/67360231/210404330-8393238d-91ba-4cb9-9d09-859873573251.png)
![Screenshot_20230103_065859](https://user-images.githubusercontent.com/67360231/210404380-2d78af2f-bd6c-40da-9d36-078069d5c872.png)
![Screenshot_20230103_065905](https://user-images.githubusercontent.com/67360231/210404396-6986cdee-fd0a-482e-ab2c-3cfa7a14ba17.png)

**Comment by slimerplanet** [comment]
The bug has been fixed
