### ISSUE TITLE
Grip Attachment 

### ISSUE THREAD

**Issue by Mysterios69** [Silverzonegames/Steampunk#7]
Attaching the grip to any weapon causes it to turn into a "null" placeholder object with the scope attachment sprite.
The attachment can not be removed, but can be replaced.
You lose the grip attachment from your inventory in the process.

![Screenshot 2023-01-03 191542](https://user-images.githubusercontent.com/121889231/210407795-5c39a718-2b7a-45ca-a294-3a9f7f7ffbd7.png)

**Comment by luukasp** [comment]
Hi, thanks for reporting this bug (too), it looks like a small reference error, we'll fix it in the next hotfix if we have time, but it's currently not a pressing issue. ~luukasp
